services:
  customer-support-api: 
    build: 
      context: .
      target: backend
    container_name: customer-support-api
    command: yarn run dev
    ports:
      - "8100:8100"
    depends_on:
      - postgres-service
    volumes:
      - ./backend:/app/backend
      - /backend/app/node_modules
  customer-support-app: 
    build: 
      context: .
      target: frontend
    container_name: customer-support-app
    command: yarn dev
    ports:
      - "8200:8200"
    depends_on:
      - customer-support-api
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
  postgres-service: 
    image: postgres:15
    container_name: postgres-service
    restart: always
    env_file:
      backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: